### ISSUE TITLE
Problems with Device42 v17.02

### ISSUE THREAD

**Issue by labskaus** [device42/jamf_to_device42_sync#6]
I have two Stages of Device42 running: v16.22 and 17.02.

With v16.22 no issues, with v17.02. I get error messages. The script is the same, only the server adsress is different

Traceback (most recent call last):
  File "/home/git/jamf_to_device42_sync-master/starter.test.py", line 145, in <module>
    print device42_api.bulk(element)
  File "/home/git/jamf_to_device42_sync-master/device42.py", line 95, in bulk
    return self._poster({'payload': json.dumps(data)}, url).json()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by cscaglioned42** [comment]
Thanks @labskaus.  I have entered an internal ticket for this issue to be looked into.
